### ISSUE TITLE
ValueError: too many values to unpack (expected 9)

### ISSUE THREAD

**Issue by nevinmusula** [nku-shengzheliu/Pytorch-TransVG#8]
when i run the evaluation part i get the following error:

Traceback (most recent call last):
  File "train.py", line 473, in <module>
    main()
  File "train.py", line 222, in main
    _ = test_epoch(test_loader, model)
  File "train.py", line 401, in test_epoch
    for batch_idx, (imgs, masks, word_id, word_mask, bbox, ratio, dw, dh, im_id) in enumerate(val_loader):
ValueError: too many values to unpack (expected 9)

what could be the problem?

**Comment by preetom-saha-arko** [comment]
@nevinmusula  Could you solve the problem? I am getting **Keyerror : 0**
